### ISSUE TITLE
Incorrect results format

### ISSUE THREAD

**Issue by overthink** [rohaanhamid/SortableChallenge#1]
Hi Rohaan.

I am trying to evaluate your solution, but the output is not in the expected format.  Relevant bit from http://sortable.com/coding-challenge/:

```
Output File
The output your solution creates should be a text file with one Result object per line.
```

Thanks,

Mark (from sortable.com)

**Comment by rohaanhamid** [comment]
Hi Mark,

I have updated the solution. Please use the files without the pretty suffix for results in the required format.

Let me know if anything else is required!

Regards,
Rohaan
